<div class="grid-60 <?php if (!$this->staticMenu): ?>prefix-20 suffix-20<?php else: ?>prefix-10 suffix-30<?php endif ?>5 tablet-grid-50 tablet-prefix-25 tablet-suffix-25 mobile-grid-100">
    <div class="grid-100 tablet-grid-100 mobile-grid-100">
        <div class="grid-45 suffix-5 tablet-grid-45 tablet-suffix-5 mobile-grid-45 mobile-suffix-5 right">J</div>
        <div class="grid-45 prefix-5 tablet-grid-45 tablet-prefix-5 mobile-grid-45 mobile-prefix-5">Next article</div>
    </div>
    <div class="grid-100 tablet-grid-100 mobile-grid-100">
        <div class="grid-45 suffix-5 tablet-grid-45 tablet-suffix-5 mobile-grid-45 mobile-suffix-5 right">K</div>
        <div class="grid-45 prefix-5 tablet-grid-45 tablet-prefix-5 mobile-grid-45 mobile-prefix-5">Previous article</div>
    </div>
    <div class="grid-100 tablet-grid-100 mobile-grid-100">
        <div class="grid-45 suffix-5 tablet-grid-45 tablet-suffix-5 mobile-grid-45 mobile-suffix-5 right">N</div>
        <div class="grid-45 prefix-5 tablet-grid-45 tablet-prefix-5 mobile-grid-45 mobile-prefix-5">Next fead</div>
    </div>
    <div class="grid-100 tablet-grid-100 mobile-grid-100">
        <div class="grid-45 suffix-5 tablet-grid-45 tablet-suffix-5 mobile-grid-45 mobile-suffix-5 right">M</div>
        <div class="grid-45 prefix-5 tablet-grid-45 tablet-prefix-5 mobile-grid-45 mobile-prefix-5">Previous fead</div>
    </div>
    <div class="grid-100 tablet-grid-100 mobile-grid-100">
        <div class="grid-45 suffix-5 tablet-grid-45 tablet-suffix-5 mobile-grid-45 mobile-suffix-5 right">esc</div>
        <div class="grid-45 prefix-5 tablet-grid-45 tablet-prefix-5 mobile-grid-45 mobile-prefix-5">Hide shown article</div>
    </div>
    <div class="grid-100 tablet-grid-100 mobile-grid-100">
        <div class="grid-45 suffix-5 tablet-grid-45 tablet-suffix-5 mobile-grid-45 mobile-suffix-5 right">U</div>
        <div class="grid-45 prefix-5 tablet-grid-45 tablet-prefix-5 mobile-grid-45 mobile-prefix-5">Unread / read shown articlee</div>
    </div>
    <div class="grid-100 tablet-grid-100 mobile-grid-100">
        <div class="grid-45 suffix-5 tablet-grid-45 tablet-suffix-5 mobile-grid-45 mobile-suffix-5 right">F</div>
        <div class="grid-45 prefix-5 tablet-grid-45 tablet-prefix-5 mobile-grid-45 mobile-prefix-5">Add shown article to favorites or remove it</div>
    </div>
</div>

<script type="text/javascript">
    setTitle('Shortcuts');
</script>