<?php $this->headTitle()->append($this->translate->_('access_unsupported')) ?>

<div class="center">
    <br>
    <span class="icon-warning-sign big"></span>
    <h1><?php echo $this->translate->_('access_unsupported') ?></h1>
    <h2><?php echo $this->translate->_('access_unsupported_label') ?></h2>
    <p><?php echo $this->translate->_('access_unsupported_description') ?></p>
    <script type="text/javascript">
        console.log(jQuery.browser);
    </script>
</div>
