<?php
$title = $this->translate->_('about_us');
$this->headTitle()->append($title);
$color = Application_Service_Session::getInstance()->getColor();
if (null === $color)
{
    $color = 'blue';
}
?>

<div class="grid-container">
    <div class="gird-80 prefix-10 suffix-10 tablet-grid-100 mobile-grid-100 block about">
        <div class="logo-large">
            <img src="/img/<?php echo $color ?>/logo.png" alt="feader">
        </div>
        <p><?php echo $this->translate->_('about_description') ?></p>

        <h2><?php echo $this->translate->_('about_domains') ?></h2>
        <p>
            <a href="https://feader.eu" target="_blank">feader.eu</a>
            <br>
            <a href="http://feader.de" target="_blank">feader.de</a>
            <br>
            <a href="http://fead.co" target="_blank">fead.co</a>
        </p>

        <h2><?php echo $this->translate->_('imprint_further_label') ?></h2>
        <p>
            <a href="<?php echo $this->url(['controller' => 'about', 'action' => 'imprint']) ?>">
                <?php echo $this->translate->_('imprint') ?>
            </a>
            <br>
            <a href="<?php echo $this->url(['controller' => 'about', 'action' => 'dataprivacy']) ?>">
                <?php echo $this->translate->_('data_privacy') ?>
            </a>
            <br>
            <a href="<?php echo $this->url(['controller' => 'about', 'action' => 'terms']) ?>">
                <?php echo $this->translate->_('terms') ?>
            </a>
        </p>
    </div>
</div>