<div class="grid-25 tablet-push-33 mobile-grid-100">
    <div class="box">
        <h2>Users</h2>
        <div class="clear"></div>
        <a href="<?php echo $this->url(['controller' => 'admin', 'action' => 'user']) ?>">User Management</a>
    </div>
</div>

<div class="grid-25 tablet-push-33 mobile-grid-100">
    <div class="box">
        <h2>feads</h2>
        <div class="clear"></div>
        <a href="<?php echo $this->url(['controller' => 'admin', 'action' => 'fead']) ?>">fead Management</a>
    </div>
</div>

<div class="grid-25 tablet-push-33 mobile-grid-100">
    <div class="box">
        <h2>Advertisement</h2>
        <div class="clear"></div>
        <a href="<?php echo $this->url(['controller' => 'admin', 'action' => 'ad']) ?>">Ad Management</a>
    </div>
</div>

<div class="grid-25 tablet-push-33 mobile-grid-100">
    <div class="box">
        <h2>Blog</h2>
        <div class="clear"></div>
        <a href="<?php echo $this->url(['controller' => 'blog', 'action' => 'compose']) ?>">Post</a>
    </div>
</div>

<script type="text/javascript">
    setTitle('Admin panel');
</script>
