<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
	<channel>
		<title>feader Blog</title>
		<link>https://www.feader.eu/blog</link>
		<description>RSS Feed des feader Blogs</description>
		<language>de-de</language>
		<copyright>Manuel Schächinger</copyright>
		<pubDate>Mon, 4 Nov 2013 00:26:31 +0100</pubDate>

		<image>
			<url>https://www.feader.eu/img/icon.png</url>
			<title>feader RSS-Feed</title>
			<link>https://www.feader.eu/blog</link>
		</image>

		<item>
			<title>feader’s RSS-Feed ist verfügbar</title>
			<description>
				feader hat jetzt auch einen eigenen RSS-Feed!
			</description>
			<link>
				https://www.feader.eu/blog/index/id/M6rd3w
			</link>
			<author>Manuel Schächinger</author>
			<guid isPermalink="false">feader_M6rd3w</guid>
			<pubDate>Mon, 4 Nov 2013 00:26:31</pubDate>
		</item>
	</channel>
</rss>
